### ISSUE TITLE
Cannot create container for service ve_server: No command specified

### ISSUE THREAD

**Issue by e-e** [Kimtaro/docker-ve-server#2]
In my `docker-compose.yml` I have this as a service like:

```
ve_server:
    image: kimtaro/ve-server:latest
    networks:
      - app_backend
    ports:
      - "4567:4567"
    restart: always
```

However, running `docker-compose up` results in `Cannot create container for service ve_server: No command specified` Is this a dockerfile / docker-compose version issue?
